spring.application.name=fileservice
server.port=8080

minio.endpoint=minio-storage
minio.port=9000
minio.access-key=admin
minio.secret-key=admin1234
minio.bucket-name=fashionconstruct

# Actuator configuration
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.export.prometheus.enabled=true
